apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    kubernetes.io/metadata.name: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    kubernetes.io/metadata.name: backend
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    pods: "10"
    requests.cpu: "1000m"
    requests.memory: "1.5Gi"
    limits.cpu: "1000m"
    limits.memory: "1.5Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
spec:
  hard:
    pods: "3"
    requests.cpu: "1000m"
    requests.memory: "1.0Gi"
    limits.cpu: "1000m"
    limits.memory: "1.0Gi"